// Generated by CoffeeScript 1.9.1

/* Allows safe, dyamic creation of namespaces. */
var namespace;

namespace = function(id) {
  var i, len, path, ref, results, root;
  root = self;
  ref = id.split('.');
  results = [];
  for (i = 0, len = ref.length; i < len; i++) {
    path = ref[i];
    results.push(root = root[path] != null ? root[path] : root[path] = {});
  }
  return results;
};


/* RequestAnimationFrame shim. */

(function() {
  var i, len, time, vendor, vendors;
  time = 0;
  vendors = ['ms', 'moz', 'webkit', 'o'];
  for (i = 0, len = vendors.length; i < len; i++) {
    vendor = vendors[i];
    if (!(!window.requestAnimationFrame)) {
      continue;
    }
    window.requestAnimationFrame = window[vendor + 'RequestAnimationFrame'];
    window.cancelAnimationFrame = window[vendor + 'CancelAnimationFrame'];
  }
  if (!window.requestAnimationFrame) {
    window.requestAnimationFrame = function(callback, element) {
      var delta, now, old;
      now = new Date().getTime();
      delta = Math.max(0, 16 - (now - old));
      setTimeout((function() {
        return callback(time + delta);
      }), delta);
      return old = now + delta;
    };
  }
  if (!window.cancelAnimationFrame) {
    return window.cancelAnimationFrame = function(id) {
      return clearTimeout(id);
    };
  }
})();
