// Generated by CoffeeScript 1.9.1
var BallPitDemo,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

BallPitDemo = (function(superClass) {
  extend(BallPitDemo, superClass);

  function BallPitDemo() {
    return BallPitDemo.__super__.constructor.apply(this, arguments);
  }

  BallPitDemo.prototype.setup = function(full) {
    var bounds, collide, gravity, i, j, max, min, p, ref, repulsion, results;
    if (full == null) {
      full = true;
    }
    BallPitDemo.__super__.setup.call(this, full);
    min = new Vector(0.0, 0.0);
    max = new Vector(this.width, this.height);
    bounds = new EdgeBounce(min, max);
    this.physics.integrator = new Verlet();
    collide = new Collision();
    max = full ? 400 : 200;
    gravity = new ConstantForce(new Vector(0.0, 300.0));
    repulsion = new Attraction(this.mouse.pos, 200, -1000);
    results = [];
    for (i = j = 0, ref = max; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      p = new Particle(Random(0.1, 3.0));
      p.setRadius(p.mass * 4);
      p.moveTo(new Vector(Random(this.width), Random(this.height)));
      p.behaviours.push(repulsion);
      p.behaviours.push(gravity);
      p.behaviours.push(bounds);
      p.behaviours.push(collide);
      collide.pool.push(p);
      results.push(this.physics.particles.push(p));
    }
    return results;
  };

  return BallPitDemo;

})(Demo);
