// Generated by CoffeeScript 1.9.1
var LettersDemo,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

LettersDemo = (function(superClass) {
  extend(LettersDemo, superClass);

  function LettersDemo() {
    return LettersDemo.__super__.constructor.apply(this, arguments);
  }

  LettersDemo.prototype.setup = function(full) {
    var bounds, center, collide, gravity, i, j, max, min, p, p1, p2, repulsion, results, s, spring, v2;
    if (full == null) {
      full = true;
    }
    LettersDemo.__super__.setup.call(this, full);
    min = new Vector(0.0, 0.0);
    max = new Vector(this.width, this.height);
    bounds = new EdgeBounce(min, max);
    this.physics.integrator = new Verlet();
    center = new Vector(this.width * 0.5, this.height * 0.5);
    v2 = center.clone();
    v2.scale(0.5);
    p1 = new Particle(0.1);
    p1.fixed = true;
    p1.moveTo(center);
    p2 = new Particle(0.1);
    p2.fixed = true;
    p2.moveTo(v2);
    s = new Spring(p1, p2);
    this.physics.springs.push(s);
    spring = new SpringBounce(center, v2);
    gravity = new ConstantForce(new Vector(0.0, 300.0));
    repulsion = new Attraction(this.mouse.pos, 200, -2000);
    collide = new Collision();
    max = full ? 400 : 200;
    results = [];
    for (i = j = 0; j <= 0; i = ++j) {
      p = new Particle(Random(0.1, 3.0));
      p.setRadius(p.mass * 4);
      p.moveTo(new Vector(Random(this.width), Random(this.height)));
      p.behaviours.push(repulsion);
      p.behaviours.push(gravity);
      p.behaviours.push(bounds);
      p.behaviours.push(spring);
      p.behaviours.push(collide);
      collide.pool.push(p);
      results.push(this.physics.particles.push(p));
    }
    return results;
  };

  return LettersDemo;

})(Demo);
