// Generated by CoffeeScript 1.9.1

/* Integrator */
var Integrator;

Integrator = (function() {
  function Integrator() {}

  Integrator.prototype.integrate = function(particles, dt) {};

  return Integrator;

})();
