// Generated by CoffeeScript 1.9.1

/* Behaviour */
var Behaviour;

Behaviour = (function() {
  Behaviour.GUID = 0;

  function Behaviour() {
    this.GUID = Behaviour.GUID++;
    this.interval = 1;
  }

  Behaviour.prototype.apply = function(p, dt, index) {
    var name;
    return (p[name = '__behaviour' + this.GUID] != null ? p[name] : p[name] = {
      counter: 0
    }).counter++;
  };

  return Behaviour;

})();
